### ISSUE TITLE
Opening the Password menu crashes the game

### ISSUE THREAD

**Issue by TriumphantBass** [JarnoWesthof/TsRandomizer#2]
Hi, I encountered a crash trying to enter the Password menu at the very start of the game.

I recognize that this is an edge case as passwords are not expected to be used during the randomizer, but I was just trying to enter the Kickstarter backer password to unlock the alternate familiar skins.

Would it be possible to either grey-out and disable the password menu, or to leave it enabled but fix the crash? (also if it's disabled rather than fixed, it would be a nice-to-have if the alternate familiar skins could be enabled via a different method, such as a flag on seed creation)

For reference, the code also includes Umbra orb and Merchant Crow familiar, so if a flag for the skins is possible that would be preferable so that those items can't be acquired early.

Crash log as follows.

```
Context:
Timespinner Version: 1.032, TsRandomizer Version: 0.0.9.8
Level: 0, Room: 3, Seed: 4BC2EF4201

Exceptions:
Exception: Object reference not set to an instance of an object.
   at TsRandomizer.Screens.SeedSelection.SeedSelectionMenuScreen.Update(GameTime gameTime, InputState input)
   at TsRandomizer.Screens.ScreenManager.UpdateScreens(GameTime gameTime)
   at TsRandomizer.Screens.ScreenManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Timespinner.TimespinnerGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at TsRandomizer.Program.<>c.<StartTimeSpinner>b__5_0()
   at TsRandomizer.Program.WithExceptionLogging(Action action)

```

**Comment by TriumphantBass** [comment]
Looking closer, the skin items are "Wyrm Brooch" and "Greed Brooch". If those could be included in the item pool or in flags, there would be no need for the password menu, as Empire orb, Nightmare Mode, and Merchant Crow are already available without passwords.

**Comment by JarnoWesthof** [comment]
Thanks this has been resolved in latest commit, it should arrive in version 0.9.9
