### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by Antendren** [JarnoWesthof/TsRandomizer#62]
I updated the randomizer, and now it crashes after pressing a button on the opening screen (where it says "press START to...").  I don't have Archipelago installed.  Full crash log:

Context:
Timespinner Version: 1.033, TsRandomizer Version: 0.1.4.2
Level: 0, Room: 0, Seed: 

Exceptions:
Exception: Method not found: 'Archipelago.MultiClient.Net.Helpers.ArchipelagoSocketHelper Archipelago.MultiClient.Net.ArchipelagoSession.get_Socket()'.
   at TsRandomizer.Archipelago.Client.Disconnect()
   at TsRandomizer.Screens.MainMenuScreen.Initialize(ItemLocationMap itemLocationMap, GCM gameContentManager)
   at TsRandomizer.Screens.ScreenManager.DetectNewScreens()
   at TsRandomizer.Screens.ScreenManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Timespinner.TimespinnerGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at TsRandomizer.Program.<>c.<StartTimeSpinner>b__7_0()
   at TsRandomizer.Program.WithExceptionLogging(Action action)

**Comment by Antendren** [comment]
Please ignore.  I hadn't updated the dlls.
