### ISSUE TITLE
Crash on new game

### ISSUE THREAD

**Issue by SenseiLeRoof** [JarnoWesthof/TsRandomizer#78]
CTD before new game intro would have started.

Context:
Timespinner Version: 1.033, TsRandomizer Version: 0.1.5.0
Level: 0, Room: 0, Seed: 4BF2588E00001528

Exceptions:
Exception: Unable to cast object of type 'System.Boolean' to type 'System.String'.
   at TsRandomizer.Screens.GameplayScreen.Initialize(ItemLocationMap _, GCM gameContentManager)
   at TsRandomizer.Screens.ScreenManager.DetectNewScreens()
   at TsRandomizer.Screens.ScreenManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Timespinner.TimespinnerGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at TsRandomizer.Program.<>c.<StartTimeSpinner>b__7_0()
   at TsRandomizer.Program.WithExceptionLogging(Action action)

Update: It's apparently linked to the "Start with Meyef" option.

**Comment by JarnoWesthof** [comment]
Thanks for reporting, this should be fixed in the 1.6.0 release https://github.com/JarnoWesthof/TsRandomizer/releases/tag/v1.6.0
